<?php

/**
 * @file
 * Contains main functions and hooks for img_aspect_ratio_validation module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\FileInterface;

/**
 * Implements hook_help().
 */
function ogilvy_cloudflare_cache_purge_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.img_aspect_ratio_validation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module helps us to validate the image based on the aspect ratio configured againest the image field.') . '</p>';
      return ['#markup' => $output];
  }
}

/**
 * Verifies that image aspect ratio as per the configurable values.
 *
 * Non-image files will be ignored.
 *
 * @param \Drupal\file\FileInterface $file
 *   A file entity.
 * @param string $aspect_ratio
 *   (optional) A string in the form WIDTH:HEIGHT; for example, '3:2'.
 *
 * @return array
 *   containing the error message will be returned.
 */
function img_aspect_ratio_validation_image_file(FileInterface $file, $aspect_ratio = '') {
  $image_factory = \Drupal::service('image.factory');
  $image = $image_factory->get($file->getFileUri());
  if ($image->isValid()) {
    if (!empty($aspect_ratio)) {
      list($width, $height) = explode(':', $aspect_ratio);
      $x = number_format((float) ($width / $height), 2, '.', '');
      $y = number_format((float) ($image->getWidth() / $image->getHeight()), 2, '.', '');
      if ($x != $y) {
        $errors[] = t('The given image aspect ratio %$y not matching with actual aspect ratio %$x',
        [
          '%$y' => img_aspect_ratio_validation_calculate_ratio($image->getWidth(), $image->getHeight()),
          '%$x' => $aspect_ratio,
        ]);
        return $errors;
      }
    }
  }
}

/**
 * Calculate the aspect ration based on the width and height.
 *
 * @param int $a
 *   A file entity.
 * @param int $b
 *   Intger.
 *
 * @return string
 *   containing aspect ratio
 */
function img_aspect_ratio_validation_calculate_ratio($a, $b) {
  $gcd = '';
  $gcd = function ($a, $b) use (&$gcd) {
    return ($a % $b) ? $gcd($b, $a % $b) : $b;
  };
  $g = $gcd($a, $b);
  return $a / $g . ':' . $b / $g;
}
