<?php

/**
 * @file
 * Contains main functions and hooks for img_aspect_ratio_validation module.
 */

use Drupal\file\FileInterface;

/**
 * Verifies that image aspect ratio as per the configurable values.
 *
 * Non-image files will be ignored.
 *
 * @param \Drupal\file\FileInterface $file
 *   A file entity.
 * @param string $aspect_ratio
 *   (optional) A string in the form WIDTH:HEIGHT; for example, '3:2'.
 *
 * @return array
 *   containing the error message will be returned.
 */
function file_validate_image_aspect_ratio_validation(FileInterface $file, $aspect_ratio = '') {
  $image_factory = \Drupal::service('image.factory');
  $image = $image_factory->get($file->getFileUri());
  if ($image->isValid()) {
    if (isset($aspect_ratio) && !empty($aspect_ratio)) {
      list($width, $height) = explode(':', $aspect_ratio);
      $x = number_format((float) ($width / $height), 2, '.', '');
      $y = number_format((float) ($image->getWidth() / $image->getHeight()), 2, '.', '');
      if ($x != $y) {
        $errors[] = t('The given image aspect ratio %$y not matching with actual aspect ratio %$x',
        [
          '%$y' => calculate_ratio($image->getWidth(), $image->getHeight()),
          '%$x' => $aspect_ratio,
        ]);
        return $errors;
      }
    }
  }
}

/**
 * Calculate the aspect ration based on the width and height.
 *
 * @param int $a
 *   A file entity.
 * @param int $b
 *   Intger.
 *
 * @return string
 *   containing aspect ratio
 */
function calculate_ratio($a, $b) {
  $gcd = '';
  $gcd = function ($a, $b) use (&$gcd) {
    return ($a % $b) ? $gcd($b, $a % $b) : $b;
  };
  $g = $gcd($a, $b);
  return $a / $g . ':' . $b / $g;
}
